name: Trollskogen
version: ${project.version}
main: com.github.hornta.trollskogen.Main
api-version: 1.13
depend: [HolographicDisplays]
commands:
  ts:
  hat:
  announcement:
  effect:
  ban:
  unban:
  banlist:
  home:
  sethome:
  delhome:
  homes:
  maintenance:
  phome:
  verify:
  callevent:
  race:
  playsong:
  stopsong:
