name: Trollskogen
version: ${project.version}
main: com.github.hornta.trollskogen.Main
api-version: 1.13
softdepend:
  - LuckPerms
  - SassySpawn
commands:
  ts:
  hat:
  announcement:
  effect:
  ban:
  tmpban:
  unban:
  banlist:
  home:
  sethome:
  delhome:
  openhome:
  closehome:
  homes:
  togglehomecmds:
  maintenance:
  ahome:
  phome:
  verify:
  callevent:
  playsong:
  stopsong:
  skipwait:
  yes:
  no:
